name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test-in-node:
    uses: ./.github/workflows/tests-core.yml
    with:
      env-name: Node.JS
      test-command: pnpm run test
  test-in-browsers:
    if: ${{ false }}  # disable for now
    strategy:
      matrix:
        browser:
          - chrome
          - firefox
          - safari
    uses: ./.github/workflows/tests-core.yml
    with:
      env-name: ${{matrix.browser}}
      test-command: BROWSER_TO_TEST=${{matrix.browser}} pnpm run test-in-browser
    
 