name: Run Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  setup-for-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install NPM modules
        run: "pnpm i"
  test-in-node:
    runs-on: ubuntu-latest
    needs: setup-for-tests
    steps:
      - name: "Run tests in Node.JS"
        run: "pnpm run test"
  test-in-browsers:
    runs-on: ubuntu-latest
    needs: setup-for-tests
    strategy:
      matrix:
        browser:
          - chrome
          - firefox
          - safari
    steps:
      - name: "Run tests in ${{matrix.browser}}"
        run: "BROWSER_TO_TEST=${{matrix.browser}} pnpm run test-in-browser"
    
 