name: Run Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test-in-node:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/setups-for-tests.yml
    steps:
      - name: "Run tests in Node.JS"
        run: "pnpm run test"
  test-in-browsers:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/setups-for-tests.yml
    strategy:
      matrix:
        browser:
          - chrome
          - firefox
          - safari
    steps:
      - name: "Run tests in ${{matrix.browser}}"
        run: "BROWSER_TO_TEST=${{matrix.browser}} pnpm run test-in-browser"
    
 